substitutions:
  device_name: air-quality-sensor
  uart_tx_pin: GPIO26
  uart_rx_pin: GPIO27
  dht_pin: GPIO18
  switch_pin: GPIO14

esphome:
  name: '$device_name'
  platform: ESP32
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.247
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '$device_name'
    password: !secret fallback_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret esphome_web_username
    password: !secret esphome_web_password

uart:
  tx_pin: $uart_tx_pin
  rx_pin: $uart_rx_pin
  baud_rate: 9600

binary_sensor:
  - platform: status
    name: "Air Quality Meter Status"

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
  - platform: dht
    pin: $dht_pin
    temperature:
      name: "Air quality meter Temperature"
    humidity:
      name: "Air quality meter Humidity"
    model: DHT11
    update_interval: 20s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Air Quality Sensor - IP Address"
      icon: mdi:wifi

switch:
  - platform: gpio
    pin: 
      number: $switch_pin
    id: pms_set
    name: "Start measuring"
  
interval:
  - interval: 180s
    then:
      - switch.turn_on: pms_set
      - delay: 40s
      - switch.turn_off: pms_set
